export default {
  DELETE_STOCKITEM_REQUEST: "DELETE_STOCKITEM_REQUEST",
  DELETE_STOCKITEM_SUCCESS: "DELETE_STOCKITEM_SUCCESS",

  SEARCH_STOCKITEMS_REQUEST: "SEARCH_STOCKITEMS_REQUEST",
  SEARCH_STOCKITEMS_SUCCESS: "SEARCH_STOCKITEMS_SUCCESS",

  SEARCH_USER_STOCKITEMS_REQUEST: "SEARCH_USER_STOCKITEMS_REQUEST",
  SEARCH_USER_STOCKITEMS_SUCCESS: "SEARCH_USER_STOCKITEMS_SUCCESS",

  GET_STOCKITEMS_REQUEST: "GET_STOCKITEMS_REQUEST",
  GET_STOCKITEMS_SUCCESS: "GET_STOCKITEMS_SUCCESS",

  CREATE_STOCKITEMS_REQUEST: "CREATE_STOCKITEMS_REQUEST",
  CREATE_STOCKITEMS_SUCCESS: "CREATE_STOCKITEMS_SUCCESS",

  STOCKITEMS_LOADING: "STOCKITEMS_LOADING",
};
