export default {
  SEARCH_BUSINESS_REPORTS_REQUEST: "SEARCH_BUSINESS_REPORTS_REQUEST",
  SEARCH_BUSINESS_REPORTS_SUCCESS: "SEARCH_BUSINESS_REPORTS_SUCCESS",

  BUSINESS_REPORTS_LOADING: "BUSINESS_REPORTS_LOADING",
};
