export default {
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",

  GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",

  ADD_LOADING_USER: "ADD_LOADING_USER",
  ADD_LOADING_USER_DATA: "ADD_LOADING_USER_DATA",
  ADD_USER_LOADING_AUTH: "ADD_USER_LOADING_AUTH",
};
