export const menuData = (pathName: string, brnachId: string, token: string) => {
  // const DashboardData = [
  //   {
  //     icon: "/images/brand.png",
  //     name: "Sub Dashboard",
  //     link: `/dashboard`,
  //     count: -1,
  //     subMenu: [],
  //     active: pathName?.includes("dashboard"),
  //   },
  // ];
  return [
    {
      icon: "/images/dashboard.png",
      name: "Dashboard",
      link: "/dashboard",
      count: -1,
      subMenu: [],
      active: pathName?.includes("dashboard"),
    },
    {
      icon: "/images/dashboard.png",
      name: "System Logs",
      link: "/system-logs/1",
      count: -1,
      subMenu: [],
      active: pathName?.includes("system-logs"),
    },
    {
      icon: "/images/dashboard.png",
      name: "Notifications",
      link: "/notifications/1",
      count: -1,
      subMenu: [],
      active: pathName?.includes("notifications"),
    },
    {
      icon: "/images/dashboard.png",
      name: "Stock Items",
      link: "/stockitems/1",
      count: -1,
      subMenu: [],
      active: pathName?.includes("stockitems"),
    },
    {
      icon: "/images/dashboard.png",
      name: "Entities",
      link: "/entities/1",
      count: -1,
      subMenu: [],
      active: pathName?.includes("entities"),
    },
    {
      icon: "/images/dashboard.png",
      name: "Customer Accounts",
      link: "/customer-accounts/1",
      count: -1,
      subMenu: [],
      active: pathName?.includes("customer-accounts"),
    },
    {
      icon: "/images/dashboard.png",
      name: "Business Accounts",
      link: "/business-accounts/1",
      count: -1,
      subMenu: [],
      active: pathName?.includes("business-accounts"),
    },
    // {
    //   icon: "/images/dashboard.png",
    //   name: "Customer Reports",
    //   link: "/customer-reports/1",
    //   count: -1,
    //   subMenu: [],
    //   active: pathName?.includes("customer-reports"),
    // },
    // {
    //   icon: "/images/dashboard.png",
    //   name: "Business Reports",
    //   link: "/business-reports/1",
    //   count: -1,
    //   subMenu: [],
    //   active: pathName?.includes("business-reports"),
    // },
    // {
    //   icon: "/images/dashboard.png",
    //   name: "Reports",
    //   link: "/reports",
    //   count: -1,
    //   subMenu: [],
    //   active: pathName?.includes("reports"),
    // },
    // {
    //   icon: "/images/dashboard.png",
    //   name: "Subscriptions",
    //   link: "/subscription-reports/1",
    //   count: -1,
    //   subMenu: [],
    //   active: pathName?.includes("subscription-reports"),
    // },
    {
      icon: "/images/dashboard.png",
      name: "Manage Admins",
      link: "/manage-admins/1",
      count: -1,
      subMenu: [],
      active: pathName?.includes("manage-admins"),
    },
  ];
};
