export default {
  GET_ALL_SUPER_ADMINS_REQUEST: "GET_ALL_SUPER_ADMINS_REQUEST",
  GET_ALL_SUPER_ADMINS_SUCCESS: "GET_ALL_SUPER_ADMINS_SUCCESS",

  CREATE_SUPER_ADMIN_REQUEST: "CREATE_SUPER_ADMIN_REQUEST",
  CREATE_SUPER_ADMIN_SUCCESS: "CREATE_SUPER_ADMIN_SUCCESS",

  SUPER_ADMIN_LOADING: "SUPER_ADMIN_LOADING",
};
