export default {
  SEARCH_ALL_CUSTOMERS_REQUEST: "SEARCH_ALL_CUSTOMERS_REQUEST",
  SEARCH_ALL_CUSTOMERS_SUCCESS: "SEARCH_ALL_CUSTOMERS_SUCCESS",

  GET_CUSTOMER_REQUEST: "GET_CUSTOMER_REQUEST",
  GET_CUSTOMER_SUCCESS: "GET_CUSTOMER_SUCCESS",

  CREATE_CUSTOMER_REQUEST: "CREATE_CUSTOMER_REQUEST",
  CREATE_CUSTOMER_SUCCESS: "CREATE_CUSTOMER_SUCCESS",

  UPDATE_CUSTOMER_REQUEST: "UPDATE_CUSTOMER_REQUEST",
  UPDATE_CUSTOMER_SUCCESS: "UPDATE_CUSTOMER_SUCCESS",

  APPLY_RECIEVE_PROMOTION_REQUEST: "APPLY_RECIEVE_PROMOTION_REQUEST",
  APPLY_RECIEVE_PROMOTION_SUCCESS: "APPLY_RECIEVE_PROMOTION_SUCCESS",

  CUSTOMERS_LOADING: "NOTIFICATIONS_LOADING",
};
