export default {
  SEARCH_CUSTOMER_REPORTS_REQUEST: "SEARCH_CUSTOMER_REPORTS_REQUEST",
  SEARCH_CUSTOMER_REPORTS_SUCCESS: "SEARCH_CUSTOMER_REPORTS_SUCCESS",

  CUSTOMER_REPORTS_LOADING: "CUSTOMER_REPORTS_LOADING",
};
