export default {
  SEARCH_ALL_BUSINESS_ACCS_REQUEST: "SEARCH_ALL_BUSINESS_ACCS_REQUEST",
  SEARCH_ALL_BUSINESS_ACCS_SUCCESS: "SEARCH_ALL_BUSINESS_ACCS_SUCCESS",

  GET_BUSINESS_ACC_REQUEST: "GET_BUSINESS_ACC_REQUEST",
  GET_BUSINESS_ACC_SUCCESS: "GET_BUSINESS_ACC_SUCCESS",

  BUSINESS_LOADING: "BUSINESS_LOADING",
};
