export default {
  SEARCH_ALL_BUSINESS_ACCS_REQUEST: "SEARCH_ALL_BUSINESS_ACCS_REQUEST",
  SEARCH_ALL_BUSINESS_ACCS_SUCCESS: "SEARCH_ALL_BUSINESS_ACCS_SUCCESS",

  BUSINESS_LOADING: "BUSINESS_LOADING",
};
