export default {
  DELETE_TUTORIAL_REQUEST: "DELETE_TUTORIAL_REQUEST",
  DELETE_TUTORIAL_SUCCESS: "DELETE_TUTORIAL_SUCCESS",

  SEARCH_TUTORIALS_REQUEST: "SEARCH_TUTORIALS_REQUEST",
  SEARCH_TUTORIALS_SUCCESS: "SEARCH_TUTORIALS_SUCCESS",

  SEARCH_USER_TUTORIALS_REQUEST: "SEARCH_USER_TUTORIALS_REQUEST",
  SEARCH_USER_TUTORIALS_SUCCESS: "SEARCH_USER_TUTORIALS_SUCCESS",

  GET_TUTORIALS_REQUEST: "GET_TUTORIALS_REQUEST",
  GET_TUTORIALS_SUCCESS: "GET_TUTORIALS_SUCCESS",

  CREATE_TUTORIALS_REQUEST: "CREATE_TUTORIALS_REQUEST",
  CREATE_TUTORIALS_SUCCESS: "CREATE_TUTORIALS_SUCCESS",

  EDIT_TUTORIALS_REQUEST: "EDIT_TUTORIALS_REQUEST",
  EDIT_TUTORIALS_SUCCESS: "EDIT_TUTORIALS_SUCCESS",

  TUTORIALS_LOADING: "TUTORIALS_LOADING",
};
