export default {
  SUBSCRIPTION_REPORTS_DTD_REQUEST: "SUBSCRIPTION_REPORTS_DTD_REQUEST",
  SUBSCRIPTION_REPORTS_DTD_SUCCESS: "SUBSCRIPTION_REPORTS_DTD_SUCCESS",

  SUBSCRIPTION_REPORTS_WTW_REQUEST: "SUBSCRIPTION_REPORTS_WTW_REQUEST",
  SUBSCRIPTION_REPORTS_WTW_SUCCESS: "SUBSCRIPTION_REPORTS_WTW_SUCCESS",

  SUBSCRIPTION_REPORTS_MTM_REQUEST: "SUBSCRIPTION_REPORTS_MTM_REQUEST",
  SUBSCRIPTION_REPORTS_MTM_SUCCESS: "SUBSCRIPTION_REPORTS_MTM_SUCCESS",

  SUBSCRIPTION_REPORTS_YTY_REQUEST: "SUBSCRIPTION_REPORTS_YTY_REQUEST",
  SUBSCRIPTION_REPORTS_YTY_SUCCESS: "SUBSCRIPTION_REPORTS_YTY_SUCCESS",

  SUBSCRIPTION_REPORTS_LOADING: "SUBSCRIPTION_REPORTS_LOADING",
};
