export default {
  DELETE_SYSTEM_LOG_REQUEST: "DELETE_SYSTEM_LOG_REQUEST",
  DELETE_SYSTEM_LOG_SUCCESS: "DELETE_SYSTEM_LOG_SUCCESS",

  SEARCH_SYSTEM_LOGS_REQUEST: "SEARCH_SYSTEM_LOGS_REQUEST",
  SEARCH_SYSTEM_LOGS_SUCCESS: "SEARCH_SYSTEM_LOGS_SUCCESS",

  GET_SYSTEM_LOGS_REQUEST: "GET_SYSTEM_LOGS_REQUEST",
  GET_SYSTEM_LOGS_SUCCESS: "GET_SYSTEM_LOGS_SUCCESS",

  SYSTEM_LOGS_LOADING: "SYSTEM_LOGS_LOADING",
};
