export default {
  SEARCH_LOGS_REPORTS_REQUEST: "SEARCH_LOGS_REPORTS_REQUEST",
  SEARCH_LOGS_REPORTS_SUCCESS: "SEARCH_LOGS_REPORTS_SUCCESS",

  SEARCH_SUBSCRIPTIONS_REPORTS_REQUEST: "SEARCH_SUBSCRIPTIONS_REPORTS_REQUEST",
  SEARCH_SUBSCRIPTIONS_REPORTS_SUCCESS: "SEARCH_SUBSCRIPTIONS_REPORTS_SUCCESS",

  REPORTS_LOADING: "REPORTS_LOADING",
};
