export default {
  DELETE_ENTITY_REQUEST: "DELETE_ENTITY_REQUEST",
  DELETE_ENTITY_SUCCESS: "DELETE_ENTITY_SUCCESS",

  SEARCH_ENTITY_REQUEST: "SEARCH_ENTITY_REQUEST",
  SEARCH_ENTITY_SUCCESS: "SEARCH_ENTITY_SUCCESS",

  SEARCH_USER_ENTITY_REQUEST: "SEARCH_USER_ENTITY_REQUEST",
  SEARCH_USER_ENTITY_SUCCESS: "SEARCH_USER_ENTITY_SUCCESS",

  GET_ENTITY_REQUEST: "GET_ENTITY_REQUEST",
  GET_ENTITY_SUCCESS: "GET_ENTITY_SUCCESS",

  CREATE_ENTITY_REQUEST: "CREATE_ENTITY_REQUEST",
  CREATE_ENTITY_SUCCESS: "CREATE_ENTITY_SUCCESS",

  ENTITY_LOADING: "ENTITY_LOADING",
};
