export default {
  DELETE_NOTIFICATION_REQUEST: "DELETE_NOTIFICATION_REQUEST",
  DELETE_NOTIFICATION_SUCCESS: "DELETE_NOTIFICATION_SUCCESS",

  SEARCH_NOTIFICATIONS_REQUEST: "SEARCH_NOTIFICATIONS_REQUEST",
  SEARCH_NOTIFICATIONS_SUCCESS: "SEARCH_NOTIFICATIONS_SUCCESS",

  SEARCH_USER_NOTIFICATIONS_REQUEST: "SEARCH_USER_NOTIFICATIONS_REQUEST",
  SEARCH_USER_NOTIFICATIONS_SUCCESS: "SEARCH_USER_NOTIFICATIONS_SUCCESS",

  GET_NOTIFICATIONS_REQUEST: "GET_NOTIFICATIONS_REQUEST",
  GET_NOTIFICATIONS_SUCCESS: "GET_NOTIFICATIONS_SUCCESS",

  CREATE_NOTIFICATIONS_REQUEST: "CREATE_NOTIFICATIONS_REQUEST",
  CREATE_NOTIFICATIONS_SUCCESS: "CREATE_NOTIFICATIONS_SUCCESS",

  NOTIFICATIONS_LOADING: "NOTIFICATIONS_LOADING",
};
